import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Home, 
  BookOpen, 
  Flower2, 
  Compass, 
  Heart, 
  Flame, 
  LogOut, 
  Sparkles, 
  CloudRain, 
  Sun 
} from 'lucide-react';
import { RoomId } from './types';

// Import subcomponents
import CustomCursor from './components/CustomCursor';
import MusicPlayer from './components/MusicPlayer';
import CottageLoader from './components/CottageLoader';
import HomeRoom from './components/HomeRoom';
import BedroomRoom from './components/BedroomRoom';
import GardenRoom from './components/GardenRoom';
import VanityRoom from './components/VanityRoom';
import BookshelfRoom from './components/BookshelfRoom';
import MemoryBoxRoom from './components/MemoryBoxRoom';
import LittleCafeRoom from './components/LittleCafeRoom';
import GuestbookRoom from './components/GuestbookRoom';
import MiniGamesRoom from './components/MiniGamesRoom';

// Static assets generated by our image-generation tool
const PINK_COTTAGE_IMAGE = '/src/assets/images/pink_cottage_loading_1782875176425.jpg';
const DREAMY_GIRL_IMAGE = '/src/assets/images/dreamy_cottage_girl_1782875190907.jpg';

const RAINDROPS = Array.from({ length: 65 }).map((_, i) => ({
  id: i,
  left: (i * 1.57) % 100, // evenly distributed initial columns
  delay: (i * 0.12) % 3, // staggered starts
  duration: 0.5 + ((i * 0.17) % 0.6), // speed variation
  height: 25 + ((i * 7) % 30), // lengths
  opacity: 0.15 + ((i * 0.05) % 0.35), // transparency
}));

interface PetalParticle {
  id: number;
  x: number;
  y: number;
  size: number;
  rotate: number;
  delay: number;
  duration: number;
  repeat?: number; // Infinity for background, 0 for bursts
}

export default function App() {
  const [currentRoom, setCurrentRoom] = useState<RoomId | 'loader' | 'closing'>('loader');
  
  // Music & audio state
  const [isPlayingMusic, setIsPlayingMusic] = useState(false);
  const [hasInteracted, setHasInteracted] = useState(false);

  // Background ambience toggles
  const [weather, setWeather] = useState<'sunshine' | 'rain'>('sunshine');
  const [floatingPetals, setFloatingPetals] = useState<PetalParticle[]>([]);

  // Rain audio references
  const rainAudioRef = React.useRef<HTMLAudioElement | null>(null);
  const rainAudioCtxRef = React.useRef<AudioContext | null>(null);
  const rainNoiseNodeRef = React.useRef<AudioBufferSourceNode | null>(null);
  const rainGainNodeRef = React.useRef<GainNode | null>(null);
  const rainIntervalRef = React.useRef<any>(null);

  const startRainSound = () => {
    try {
      // 1. Try real audio loop first (premium natural rain sound)
      if (!rainAudioRef.current) {
        const audio = new Audio('https://www.soundjay.com/nature/sounds/rain-07.mp3');
        audio.loop = true;
        audio.volume = 0.28; // soft cozy volume
        rainAudioRef.current = audio;
      }
      
      // Stop fallback synthetic sound first to prevent overlap
      stopSynthesizedRain();

      if (hasInteracted) {
        rainAudioRef.current.play().then(() => {
          console.log("High-fidelity rain audio loop started successfully.");
        }).catch((err) => {
          console.warn("Real rain audio failed or blocked, falling back to pink noise synthesizer:", err);
          startSynthesizedRain();
        });
      }
    } catch (err) {
      console.warn("Could not load real rain sound, using synthesizer fallback:", err);
      startSynthesizedRain();
    }
  };

  const startSynthesizedRain = () => {
    try {
      if (!rainAudioCtxRef.current) {
        const AudioContextClass = window.AudioContext || (window as any).webkitAudioContext;
        rainAudioCtxRef.current = new AudioContextClass();
      }
      const ctx = rainAudioCtxRef.current;
      if (ctx.state === 'suspended') {
        ctx.resume();
      }

      stopSynthesizedRain();

      // Create a 2-second buffer of Pink Noise (Paul Kellet's refined method) for an ultra-realistic cozy feel
      const bufferSize = ctx.sampleRate * 2;
      const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate);
      const data = buffer.getChannelData(0);
      
      let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1;
        b0 = 0.99886 * b0 + white * 0.0555179;
        b1 = 0.99332 * b1 + white * 0.0750759;
        b2 = 0.96900 * b2 + white * 0.1538520;
        b3 = 0.86650 * b3 + white * 0.3104856;
        b4 = 0.55000 * b4 + white * 0.5329522;
        b5 = -0.7616 * b5 - white * 0.0168980;
        data[i] = b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362;
        data[i] *= 0.11; // normalise
        b6 = white * 0.115926;
      }

      const noiseSource = ctx.createBufferSource();
      noiseSource.buffer = buffer;
      noiseSource.loop = true;

      const filter = ctx.createBiquadFilter();
      filter.type = 'lowpass';
      filter.frequency.setValueAtTime(1200, ctx.currentTime);

      const gainNode = ctx.createGain();
      gainNode.gain.setValueAtTime(0.18, ctx.currentTime); // cozy and low-key

      noiseSource.connect(filter);
      filter.connect(gainNode);
      gainNode.connect(ctx.destination);

      noiseSource.start();

      rainNoiseNodeRef.current = noiseSource;
      rainGainNodeRef.current = gainNode;

      // Subtle window pitter-patter raindrops
      rainIntervalRef.current = setInterval(() => {
        if (rainAudioCtxRef.current && rainAudioCtxRef.current.state !== 'suspended') {
          if (Math.random() > 0.3) {
            triggerRainDropTap(rainAudioCtxRef.current);
          }
        }
      }, 250);

    } catch (err) {
      console.warn("Could not start synthesized rain fallback:", err);
    }
  };

  const triggerRainDropTap = (ctx: AudioContext) => {
    if (ctx.state === 'suspended') return;
    try {
      const osc = ctx.createOscillator();
      const gainNode = ctx.createGain();
      const filter = ctx.createBiquadFilter();

      filter.type = 'bandpass';
      filter.frequency.setValueAtTime(1400 + Math.random() * 600, ctx.currentTime);
      filter.Q.setValueAtTime(2.0, ctx.currentTime);

      osc.type = 'sine';
      osc.frequency.setValueAtTime(500 + Math.random() * 300, ctx.currentTime);
      osc.frequency.exponentialRampToValueAtTime(100, ctx.currentTime + 0.04);

      gainNode.gain.setValueAtTime(0.01 + Math.random() * 0.012, ctx.currentTime);
      gainNode.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + 0.04);

      osc.connect(filter);
      filter.connect(gainNode);
      gainNode.connect(ctx.destination);

      osc.start();
      osc.stop(ctx.currentTime + 0.06);
    } catch (e) {}
  };

  const stopSynthesizedRain = () => {
    if (rainIntervalRef.current) {
      clearInterval(rainIntervalRef.current);
      rainIntervalRef.current = null;
    }
    if (rainNoiseNodeRef.current) {
      try {
        rainNoiseNodeRef.current.stop();
        rainNoiseNodeRef.current.disconnect();
      } catch (e) {}
      rainNoiseNodeRef.current = null;
    }
  };

  const stopRainSound = () => {
    // Stop real audio
    if (rainAudioRef.current) {
      try {
        rainAudioRef.current.pause();
      } catch (e) {}
    }
    // Stop synth fallback
    stopSynthesizedRain();
  };

  // Sync rain sounds with weather toggles
  useEffect(() => {
    if (weather === 'rain' && hasInteracted) {
      startRainSound();
    } else {
      stopRainSound();
    }
    return () => {
      stopRainSound();
    };
  }, [weather, hasInteracted]);

  // Trigger burst of petals (e.g. from Vanity perfume or Garden flower clicking)
  const triggerPetalShower = () => {
    // Generate a rich shower of 25 cute falling petals
    const burst: PetalParticle[] = Array.from({ length: 25 }).map((_, i) => ({
      id: Date.now() + i,
      x: Math.random() * 100,
      y: -15,
      size: Math.random() * 16 + 8,
      rotate: Math.random() * 360,
      delay: Math.random() * 0.3,
      duration: Math.random() * 3.5 + 2.5,
      repeat: 0, // Fall once!
    }));
    setFloatingPetals((prev) => [...prev, ...burst]);

    // Clean up expired burst petals after 6.5 seconds to avoid memory leak
    setTimeout(() => {
      setFloatingPetals((prev) => prev.filter((p) => p.repeat === Infinity || Date.now() - p.id < 5500));
    }, 6500);
  };

  // Automatically seed persistent background floating petals
  useEffect(() => {
    const initialPetals = Array.from({ length: 14 }).map((_, i) => ({
      id: i,
      x: Math.random() * 100,
      y: Math.random() * 100,
      size: Math.random() * 12 + 6,
      rotate: Math.random() * 360,
      delay: 0,
      duration: Math.random() * 12 + 8,
      repeat: Infinity, // Loop forever
    }));
    setFloatingPetals(initialPetals);
  }, []);

  const handleOpenDoor = () => {
    setHasInteracted(true);
    setIsPlayingMusic(true);
    setCurrentRoom('home');
  };

  const handleExitWorld = () => {
    stopRainSound();
    setCurrentRoom('closing');
  };

  const handleReenterWorld = () => {
    setCurrentRoom('home');
  };

  return (
    <div className="min-h-screen relative overflow-x-hidden flex flex-col justify-between selection:bg-pink-200">
      
      {/* Custom Sparkle Ribbon Cursor */}
      <CustomCursor />

      {/* Persistent floating floral petal elements */}
      <div className="fixed inset-0 pointer-events-none z-[80] overflow-hidden">
        {floatingPetals.map((petal) => (
          <motion.div
            key={petal.id}
            initial={{ y: '-10vh', x: `${petal.x}vw`, rotate: petal.rotate, opacity: 0 }}
            animate={{ 
              y: '110vh',
              x: `${petal.x + Math.sin(petal.id) * 12}vw`,
              rotate: petal.rotate + 360,
              opacity: [0, 0.8, 0.8, 0]
            }}
            transition={{
              duration: petal.duration,
              delay: petal.delay,
              repeat: petal.repeat === Infinity ? Infinity : 0,
              ease: 'linear'
            }}
            className="absolute text-pink-300/60 select-none text-2xl"
            style={{ fontSize: `${petal.size}px` }}
          >
            🌸
          </motion.div>
        ))}
      </div>

      {/* Weather Layer: Rain or Sunbeams */}
      <AnimatePresence>
        {weather === 'rain' && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 1 }}
            className="fixed inset-0 pointer-events-none z-[75] overflow-hidden"
          >
            {/* Soft dark rainy mist overlay */}
            <div className="absolute inset-0 bg-sky-950/15 mix-blend-multiply" />
            <div className="absolute inset-0 bg-gradient-to-b from-sky-900/10 via-transparent to-pink-900/5" />
            
            {/* High-fidelity animated falling raindrop lines */}
            {RAINDROPS.map((drop) => (
              <motion.div
                key={drop.id}
                initial={{ y: -120 }}
                animate={{ y: '105vh' }}
                transition={{
                  duration: drop.duration,
                  delay: drop.delay,
                  repeat: Infinity,
                  ease: 'linear',
                }}
                className="absolute bg-gradient-to-b from-transparent via-sky-100/60 to-white/90 rounded-full"
                style={{
                  left: `${drop.left}%`,
                  width: '1px',
                  height: `${drop.height}px`,
                  opacity: drop.opacity,
                }}
              />
            ))}
          </motion.div>
        )}
        {weather === 'sunshine' && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 1 }}
            className="fixed inset-0 pointer-events-none z-[75] overflow-hidden"
          >
            {/* Glowing cozy golden sunbeam rays in top-right */}
            <div className="absolute -top-40 -right-40 w-[600px] h-[600px] bg-gradient-to-br from-amber-200/25 to-rose-200/15 rounded-full blur-[90px] animate-pulse" />
            {/* Soft, warm, cozy ambient light cast */}
            <div className="absolute inset-0 bg-gradient-to-tr from-amber-100/10 via-transparent to-pink-100/15 mix-blend-soft-light" />
          </motion.div>
        )}
      </AnimatePresence>

      {/* Floater controls for weather toggling */}
      {currentRoom !== 'loader' && currentRoom !== 'closing' && (
        <div className="fixed top-24 right-6 z-[1000] flex flex-col gap-2">
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={() => {
              setHasInteracted(true);
              setWeather(weather === 'sunshine' ? 'rain' : 'sunshine');
            }}
            className="w-10 h-10 rounded-full glass-panel-pink flex items-center justify-center shadow-md text-[#ff808b] border border-[#ffb3b8]/40 cursor-pointer interactive-obj"
            title={`Switch to ${weather === 'sunshine' ? 'Cozy Rain' : 'Morning Sun'}`}
          >
            {weather === 'sunshine' ? <CloudRain className="w-4 h-4" /> : <Sun className="w-4 h-4" />}
          </motion.button>
        </div>
      )}

      {/* Floating Web Audio procedural music player */}
      <MusicPlayer 
        isPlaying={isPlayingMusic} 
        setIsPlaying={setIsPlayingMusic} 
        hasInteracted={hasInteracted} 
      />

      {/* MAIN SCREEN DISPATCHER */}
      <div className="flex-1 w-full flex flex-col">
        <AnimatePresence mode="wait">
          
          {/* LOADER INTRO SCREEN */}
          {currentRoom === 'loader' && (
            <motion.div
              key="loader"
              exit={{ opacity: 0, scale: 1.02 }}
              transition={{ duration: 1 }}
              className="w-full flex-1"
            >
              <CottageLoader onEnter={handleOpenDoor} pinkCottageImage={PINK_COTTAGE_IMAGE} />
            </motion.div>
          )}

          {/* ACTIVE COTTAGE WORLD LAYOUT */}
          {currentRoom !== 'loader' && currentRoom !== 'closing' && (
            <motion.div
              key="cottage-world"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="w-full flex flex-col justify-between min-h-screen"
            >
              {/* Header Ribbon Scrapbook Navigation */}
              <header className="sticky top-0 z-[90] w-full px-4 py-3 glass-panel-pink border-b border-[#ffb3b8]/30 shadow-sm flex items-center justify-between">
                
                {/* Logo */}
                <button 
                  onClick={() => setCurrentRoom('home')}
                  className="flex items-center gap-1.5 cursor-pointer interactive-obj group"
                >
                  <span className="font-serif text-xl font-bold tracking-widest text-[#5E3A3A] group-hover:text-[#ff808b] transition-colors">mysl.</span>
                  <div className="w-2 h-2 bg-[#ffb3b8] rounded-full animate-ping" />
                </button>

                {/* Ribbon Bow Nav items */}
                <nav className="hidden md:flex items-center gap-1">
                  {[
                    { id: 'home', label: '🏡 Cottage Map' },
                    { id: 'bedroom', label: '🛏️ Bedroom' },
                    { id: 'garden', label: '🌿 Garden' },
                    { id: 'vanity', label: '💄 Vanity' },
                    { id: 'bookshelf', label: '📚 Scrapbook' },
                    { id: 'guestbook', label: '✍️ Guestbook' },
                    { id: 'games', label: '🧸 Play' },
                  ].map((room) => (
                    <button
                      key={room.id}
                      onClick={() => setCurrentRoom(room.id as RoomId)}
                      className={`px-3 py-1.5 rounded-full font-serif text-xs tracking-wider transition-all cursor-pointer border interactive-obj ${
                        currentRoom === room.id
                          ? 'bg-[#ffb3b8] text-white border-white'
                          : 'bg-transparent text-[#5E3A3A] border-transparent hover:bg-[#FFEBEB]/40 hover:border-pink-100'
                      }`}
                    >
                      {room.label}
                    </button>
                  ))}
                </nav>

                {/* Utility: Exit Cottage button */}
                <div className="flex items-center gap-2">
                  {/* Mobile room index trigger */}
                  <div className="md:hidden">
                    <select
                      value={currentRoom}
                      onChange={(e) => setCurrentRoom(e.target.value as RoomId)}
                      className="px-2.5 py-1.5 bg-white border border-[#ffd6d9] rounded-xl text-xs font-serif text-[#5E3A3A] focus:outline-none focus:border-[#ff808b]"
                    >
                      <option value="home">🏡 Cottage Map</option>
                      <option value="bedroom">🛏️ Bedroom</option>
                      <option value="garden">🌿 Garden</option>
                      <option value="vanity">💄 Vanity</option>
                      <option value="bookshelf">📚 Scrapbook</option>
                      <option value="guestbook">✍️ Guestbook</option>
                      <option value="games">🧸 Play Cabinet</option>
                    </select>
                  </div>

                  <button
                    onClick={handleExitWorld}
                    className="px-3.5 py-1.5 bg-[#FFF5F6] hover:bg-[#ffebeb] border border-[#ffb3b8]/40 rounded-full text-[10px] font-serif text-[#ff808b] tracking-wider uppercase transition-all flex items-center gap-1.5 cursor-pointer interactive-obj"
                    title="Leave little world"
                  >
                    <LogOut className="w-3.5 h-3.5" />
                    <span className="hidden sm:inline">Close Cottage Door</span>
                  </button>
                </div>
              </header>

              {/* Main Room Screen Area */}
              <main className="flex-1 w-full py-8">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={currentRoom}
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -12 }}
                    transition={{ duration: 0.5, ease: 'easeOut' }}
                    className="w-full h-full"
                  >
                    {currentRoom === 'home' && (
                      <HomeRoom 
                        onNavigate={(room) => setCurrentRoom(room)} 
                        girlIllustration={DREAMY_GIRL_IMAGE} 
                      />
                    )}
                    {currentRoom === 'bedroom' && (
                      <BedroomRoom onTriggerPetals={triggerPetalShower} weather={weather} />
                    )}
                    {currentRoom === 'garden' && (
                      <GardenRoom onTriggerPetals={triggerPetalShower} />
                    )}
                    {currentRoom === 'vanity' && (
                      <VanityRoom onTriggerPetals={triggerPetalShower} />
                    )}
                    {currentRoom === 'bookshelf' && (
                      <BookshelfRoom />
                    )}
                    {currentRoom === 'memory-box' && (
                      <MemoryBoxRoom />
                    )}
                    {currentRoom === 'little-cafe' && (
                      <LittleCafeRoom />
                    )}
                    {currentRoom === 'guestbook' && (
                      <GuestbookRoom />
                    )}
                    {currentRoom === 'games' && (
                      <MiniGamesRoom />
                    )}
                  </motion.div>
                </AnimatePresence>
              </main>

              {/* Sweet bottom footer */}
              <footer className="w-full py-6 mt-12 border-t border-pink-100/40 text-center flex flex-col items-center gap-1">
                <span className="font-handwritten text-xl text-pink-300">mysl.</span>
                <span className="font-garamond italic text-xs text-[#8A7171] uppercase tracking-wider">
                  made with premium warmth and coquette cozyness • est. 2008
                </span>
              </footer>
            </motion.div>
          )}

          {/* CLOSING DOOR SCREEN */}
          {currentRoom === 'closing' && (
            <motion.div
              key="closing"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-[9999] bg-[#FAF6F0] flex flex-col items-center justify-center p-4 overflow-hidden"
            >
              {/* Sunbeams fading */}
              <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[600px] h-[600px] bg-[#FFEEDD] rounded-full blur-[100px] opacity-40 pointer-events-none" />

              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 1 }}
                className="w-full max-w-xl glass-panel-deep rounded-3xl p-6 md:p-8 flex flex-col items-center text-center shadow-2xl relative border border-[#ffb3b8]/30"
              >
                {/* Cottage illustration frame with closing overlay */}
                <div className="relative w-full aspect-[16/10] rounded-2xl overflow-hidden shadow-inner border border-stone-100 mb-8 mt-2">
                  <img
                    src={PINK_COTTAGE_IMAGE}
                    alt="Whimsical Pink Cottage Garden"
                    className="w-full h-full object-cover filter brightness-75 transition-all"
                    referrerPolicy="no-referrer"
                  />
                  {/* Closing shadows */}
                  <div className="absolute inset-0 bg-gradient-to-t from-stone-900/60 via-stone-900/40 to-transparent" />
                </div>

                <div className="flex flex-col gap-2 mb-8">
                  <h1 className="font-serif text-3xl text-[#5E3A3A] tracking-wide">
                    Thank you for visiting <span className="text-[#ff808b]">mysl.</span>
                  </h1>
                  <p className="font-garamond italic text-lg text-[#7A5A5A]">
                    "The cottage door slowly closes..."
                  </p>
                  <p className="font-garamond italic text-lg text-[#7A5A5A] mt-1">
                    See you again in my little world. ✿
                  </p>
                </div>

                {/* Back inside / Enter again button */}
                <button
                  onClick={handleReenterWorld}
                  className="px-8 py-3.5 bg-gradient-to-r from-[#ffd6d9] to-[#ffb3b8] hover:from-[#ffb3b8] hover:to-[#ff808b] text-white rounded-full font-serif tracking-widest text-sm shadow-md hover:shadow-lg transition-all border border-white/40 cursor-pointer flex items-center gap-1.5 interactive-obj"
                >
                  <Sparkles className="w-4 h-4" />
                  Enter Cottage Again
                </button>
              </motion.div>
            </motion.div>
          )}

        </AnimatePresence>
      </div>

    </div>
  );
}
